# Generated by Django 6.1 on 2026-09-14 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('school', 'School'), ('university', 'University')], default='full-time', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organisation', 'Organisation')], default='full-time', max_length=20),
        ),
    ]
