# Generated by Django 6.1 on 2026-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_alter_education_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('on going', 'On Going'), ('finished', 'FINISHED')], default='on going', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('on going', 'On Going'), ('finished', 'FINISHED')], default='on going', max_length=20),
        ),
    ]
