# Generated by Django 6.1 on 2026-09-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_experience_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('university', 'University')], default='School', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.CharField(choices=[('on going', 'On Going'), ('finished', 'Finished')], default='On Going', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('volunteer', 'Volunteer'), ('part-time', 'Part-Time'), ('full-time', 'Full-Time'), ('freelance', 'Freelance'), ('organization', 'Organization')], default='Full-Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='status',
            field=models.CharField(choices=[('on going', 'On Going'), ('finished', 'Finished')], default='On Going', max_length=20),
        ),
    ]
